name: Build and Deploy Workflow

on:
  push:
    branches:
      - main

env:
  API_KEY: ${{ secrets.API_KEY }}
  DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        
    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm run test
      
    - name: Build Application
      run: npm run build
      
    - name: Deploy to Staging
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'react-elite-staging'
        slot-name: 'staging'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: .
        enable-cshtml-rewrite: true
        enable-virtual-application: true
        virtual-application: '/'
        ignore-app-offline-true: true

    - name: Deploy to Production
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'react-elite-prod'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: .
        enable-cshtml-rewrite: true
        enable-virtual-application: true
        virtual-application: '/'
        ignore-app-offline-true: true

    - name: Send Email Notification on Failure
      if: failure()
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: 'smtp.gmail.com'
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: 'Build Failed for ReactElite-Project'
        body: 'The build for the ReactElite-Project has failed. Please check the workflow logs for more information.'
        from: 'sender@example.com'
        to: 'recipient@example.com'
